// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useQuery } from "@tanstack/react-query"

import type { GetApiDashboardBySessionKeyError } from "@shared/api/generated/types.gen.ts"

import { getDashboardBySessionKey } from "@shared/api/generated/requests/sessions/getDashboardBySessionKey.gen.ts"

type GetDashboardBySessionKeyHookData = Awaited<ReturnType<typeof getDashboardBySessionKey>>

export const getDashboardBySessionKeyQueryKey = "getDashboardBySessionKeyQueryKey"

export const getDashboardBySessionKeyQueryOptions = <
    TData = GetDashboardBySessionKeyHookData,
    TError = GetApiDashboardBySessionKeyError,
>(settings: {
    params?: Omit<UseQueryOptions<GetDashboardBySessionKeyHookData, TError, TData>, "queryKey">
    request: NonNullable<Parameters<typeof getDashboardBySessionKey>[0]>
}) =>
    queryOptions({
        queryKey: [
            getDashboardBySessionKeyQueryKey,
            ...(!!settings.request.path ? [settings.request.path] : []),
            ...(!!settings.request.query ? [settings.request.query] : []),
            ...(!!settings.request.body ? [settings.request.body] : []),
        ],
        queryFn: async () => getDashboardBySessionKey({ ...settings.request }),
        ...settings.params,
    })

export const useGetDashboardBySessionKeyQuery = <
    TData = GetDashboardBySessionKeyHookData,
    TError = GetApiDashboardBySessionKeyError,
>(
    ...args: Parameters<typeof getDashboardBySessionKeyQueryOptions<TData, TError>>
) => useQuery(getDashboardBySessionKeyQueryOptions<TData, TError>(...args))
