// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query"

import { useMutation } from "@tanstack/react-query"

import type { GetApiSessionsError } from "@shared/api/generated/types.gen.ts"

import { getSessions } from "@shared/api/generated/requests/sessions/getSessions.gen.ts"

type GetSessionsHookData = Awaited<ReturnType<typeof getSessions>>

export const getSessionsMutationKey = "getSessionsMutationKey"

type GetSessionsMutationVariables = Parameters<typeof getSessions>[0]

export const useGetSessionsMutation = <
    TError = GetApiSessionsError,
    TContext = unknown,
>(settings?: {
    params?: UseMutationOptions<GetSessionsHookData, TError, GetSessionsMutationVariables, TContext>
    request?: NonNullable<GetSessionsMutationVariables>
}) =>
    useMutation({
        mutationKey: [getSessionsMutationKey],
        mutationFn: async (params) => getSessions({ ...settings?.request, ...params }),
        ...settings?.params,
    })
