// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useQuery } from "@tanstack/react-query"

import type { GetApiSessionsError } from "@shared/api/generated/types.gen.ts"

import { getSessions } from "@shared/api/generated/requests/sessions/getSessions.gen.ts"

type GetSessionsHookData = Awaited<ReturnType<typeof getSessions>>

export const getSessionsQueryKey = "getSessionsQueryKey"

export const getSessionsQueryOptions = <
    TData = GetSessionsHookData,
    TError = GetApiSessionsError,
>(settings?: {
    params?: Omit<UseQueryOptions<GetSessionsHookData, TError, TData>, "queryKey">
    request?: NonNullable<Parameters<typeof getSessions>[0]>
}) =>
    queryOptions({
        queryKey: [
            getSessionsQueryKey,
            ...(!!settings?.request?.path ? [settings?.request?.path] : []),
            ...(!!settings?.request?.query ? [settings?.request?.query] : []),
            ...(!!settings?.request?.body ? [settings?.request?.body] : []),
        ],
        queryFn: async () => getSessions({ ...settings?.request }),
        ...settings?.params,
    })

export const useGetSessionsQuery = <TData = GetSessionsHookData, TError = GetApiSessionsError>(
    ...args: Parameters<typeof getSessionsQueryOptions<TData, TError>>
) => useQuery(getSessionsQueryOptions<TData, TError>(...args))
