// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query"

import { useMutation } from "@tanstack/react-query"

import type { GetApiMeetingsError } from "@shared/api/generated/types.gen.ts"

import { getMeetings } from "@shared/api/generated/requests/sessions/getMeetings.gen.ts"

type GetMeetingsHookData = Awaited<ReturnType<typeof getMeetings>>

export const getMeetingsMutationKey = "getMeetingsMutationKey"

type GetMeetingsMutationVariables = Parameters<typeof getMeetings>[0]

export const useGetMeetingsMutation = <
    TError = GetApiMeetingsError,
    TContext = unknown,
>(settings?: {
    params?: UseMutationOptions<GetMeetingsHookData, TError, GetMeetingsMutationVariables, TContext>
    request?: NonNullable<GetMeetingsMutationVariables>
}) =>
    useMutation({
        mutationKey: [getMeetingsMutationKey],
        mutationFn: async (params) => getMeetings({ ...settings?.request, ...params }),
        ...settings?.params,
    })
