// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

import type { GetApiDashboardBySessionKeyError } from "@shared/api/generated/types.gen.ts"

import { getDashboardBySessionKey } from "@shared/api/generated/requests/sessions/getDashboardBySessionKey.gen.ts"

type GetDashboardBySessionKeyHookData = Awaited<ReturnType<typeof getDashboardBySessionKey>>

export const getDashboardBySessionKeySuspenseQueryKey = "getDashboardBySessionKeySuspenseQueryKey"

export const getDashboardBySessionKeySuspenseQueryOptions = <
    TData = GetDashboardBySessionKeyHookData,
    TError = GetApiDashboardBySessionKeyError,
>(settings: {
    params?: Omit<
        UseSuspenseQueryOptions<GetDashboardBySessionKeyHookData, TError, TData>,
        "queryKey"
    >
    request: NonNullable<Parameters<typeof getDashboardBySessionKey>[0]>
}) =>
    queryOptions({
        queryKey: [
            getDashboardBySessionKeySuspenseQueryKey,
            ...(!!settings.request.path ? [settings.request.path] : []),
            ...(!!settings.request.query ? [settings.request.query] : []),
            ...(!!settings.request.body ? [settings.request.body] : []),
        ],
        queryFn: async () => getDashboardBySessionKey({ ...settings.request }),
        ...settings.params,
    })

export const useGetDashboardBySessionKeySuspenseQuery = <
    TData = GetDashboardBySessionKeyHookData,
    TError = GetApiDashboardBySessionKeyError,
>(
    ...args: Parameters<typeof getDashboardBySessionKeySuspenseQueryOptions<TData, TError>>
) => useSuspenseQuery(getDashboardBySessionKeySuspenseQueryOptions<TData, TError>(...args))
