// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useQuery } from "@tanstack/react-query"

import type { GetApiMeetingsError } from "@shared/api/generated/types.gen.ts"

import { getMeetings } from "@shared/api/generated/requests/sessions/getMeetings.gen.ts"

type GetMeetingsHookData = Awaited<ReturnType<typeof getMeetings>>

export const getMeetingsQueryKey = "getMeetingsQueryKey"

export const getMeetingsQueryOptions = <
    TData = GetMeetingsHookData,
    TError = GetApiMeetingsError,
>(settings?: {
    params?: Omit<UseQueryOptions<GetMeetingsHookData, TError, TData>, "queryKey">
    request?: NonNullable<Parameters<typeof getMeetings>[0]>
}) =>
    queryOptions({
        queryKey: [
            getMeetingsQueryKey,
            ...(!!settings?.request?.path ? [settings?.request?.path] : []),
            ...(!!settings?.request?.query ? [settings?.request?.query] : []),
            ...(!!settings?.request?.body ? [settings?.request?.body] : []),
        ],
        queryFn: async () => getMeetings({ ...settings?.request }),
        ...settings?.params,
    })

export const useGetMeetingsQuery = <TData = GetMeetingsHookData, TError = GetApiMeetingsError>(
    ...args: Parameters<typeof getMeetingsQueryOptions<TData, TError>>
) => useQuery(getMeetingsQueryOptions<TData, TError>(...args))
