// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useQuery } from "@tanstack/react-query"

import type { GetApiSessionsBySessionKeyError } from "@shared/api/generated/types.gen.ts"

import { getSessionBySessionKey } from "@shared/api/generated/requests/sessions/getSessionBySessionKey.gen.ts"

type GetSessionBySessionKeyHookData = Awaited<ReturnType<typeof getSessionBySessionKey>>

export const getSessionBySessionKeyQueryKey = "getSessionBySessionKeyQueryKey"

export const getSessionBySessionKeyQueryOptions = <
    TData = GetSessionBySessionKeyHookData,
    TError = GetApiSessionsBySessionKeyError,
>(settings: {
    params?: Omit<UseQueryOptions<GetSessionBySessionKeyHookData, TError, TData>, "queryKey">
    request: NonNullable<Parameters<typeof getSessionBySessionKey>[0]>
}) =>
    queryOptions({
        queryKey: [
            getSessionBySessionKeyQueryKey,
            ...(!!settings.request.path ? [settings.request.path] : []),
            ...(!!settings.request.query ? [settings.request.query] : []),
            ...(!!settings.request.body ? [settings.request.body] : []),
        ],
        queryFn: async () => getSessionBySessionKey({ ...settings.request }),
        ...settings.params,
    })

export const useGetSessionBySessionKeyQuery = <
    TData = GetSessionBySessionKeyHookData,
    TError = GetApiSessionsBySessionKeyError,
>(
    ...args: Parameters<typeof getSessionBySessionKeyQueryOptions<TData, TError>>
) => useQuery(getSessionBySessionKeyQueryOptions<TData, TError>(...args))
