// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query"

import { useMutation } from "@tanstack/react-query"

import type { GetApiDashboardBySessionKeyError } from "@shared/api/generated/types.gen.ts"

import { getDashboardBySessionKey } from "@shared/api/generated/requests/sessions/getDashboardBySessionKey.gen.ts"

type GetDashboardBySessionKeyHookData = Awaited<ReturnType<typeof getDashboardBySessionKey>>

export const getDashboardBySessionKeyMutationKey = "getDashboardBySessionKeyMutationKey"

type GetDashboardBySessionKeyMutationVariables = Parameters<typeof getDashboardBySessionKey>[0]

export const useGetDashboardBySessionKeyMutation = <
    TError = GetApiDashboardBySessionKeyError,
    TContext = unknown,
>(settings?: {
    params?: UseMutationOptions<
        GetDashboardBySessionKeyHookData,
        TError,
        GetDashboardBySessionKeyMutationVariables,
        TContext
    >
    request?: NonNullable<GetDashboardBySessionKeyMutationVariables>
}) =>
    useMutation({
        mutationKey: [getDashboardBySessionKeyMutationKey],
        mutationFn: async (params) => getDashboardBySessionKey({ ...settings?.request, ...params }),
        ...settings?.params,
    })
