// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

import type { GetApiSessionsError } from "@shared/api/generated/types.gen.ts"

import { getSessions } from "@shared/api/generated/requests/sessions/getSessions.gen.ts"

type GetSessionsHookData = Awaited<ReturnType<typeof getSessions>>

export const getSessionsSuspenseQueryKey = "getSessionsSuspenseQueryKey"

export const getSessionsSuspenseQueryOptions = <
    TData = GetSessionsHookData,
    TError = GetApiSessionsError,
>(settings?: {
    params?: Omit<UseSuspenseQueryOptions<GetSessionsHookData, TError, TData>, "queryKey">
    request?: NonNullable<Parameters<typeof getSessions>[0]>
}) =>
    queryOptions({
        queryKey: [
            getSessionsSuspenseQueryKey,
            ...(!!settings?.request?.path ? [settings?.request?.path] : []),
            ...(!!settings?.request?.query ? [settings?.request?.query] : []),
            ...(!!settings?.request?.body ? [settings?.request?.body] : []),
        ],
        queryFn: async () => getSessions({ ...settings?.request }),
        ...settings?.params,
    })

export const useGetSessionsSuspenseQuery = <
    TData = GetSessionsHookData,
    TError = GetApiSessionsError,
>(
    ...args: Parameters<typeof getSessionsSuspenseQueryOptions<TData, TError>>
) => useSuspenseQuery(getSessionsSuspenseQueryOptions<TData, TError>(...args))
