// This file is auto-generated by @hey-api/openapi-ts

import type { UseSuspenseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

import type { GetApiSessionsBySessionKeyError } from "@shared/api/generated/types.gen.ts"

import { getSessionBySessionKey } from "@shared/api/generated/requests/sessions/getSessionBySessionKey.gen.ts"

type GetSessionBySessionKeyHookData = Awaited<ReturnType<typeof getSessionBySessionKey>>

export const getSessionBySessionKeySuspenseQueryKey = "getSessionBySessionKeySuspenseQueryKey"

export const getSessionBySessionKeySuspenseQueryOptions = <
    TData = GetSessionBySessionKeyHookData,
    TError = GetApiSessionsBySessionKeyError,
>(settings: {
    params?: Omit<
        UseSuspenseQueryOptions<GetSessionBySessionKeyHookData, TError, TData>,
        "queryKey"
    >
    request: NonNullable<Parameters<typeof getSessionBySessionKey>[0]>
}) =>
    queryOptions({
        queryKey: [
            getSessionBySessionKeySuspenseQueryKey,
            ...(!!settings.request.path ? [settings.request.path] : []),
            ...(!!settings.request.query ? [settings.request.query] : []),
            ...(!!settings.request.body ? [settings.request.body] : []),
        ],
        queryFn: async () => getSessionBySessionKey({ ...settings.request }),
        ...settings.params,
    })

export const useGetSessionBySessionKeySuspenseQuery = <
    TData = GetSessionBySessionKeyHookData,
    TError = GetApiSessionsBySessionKeyError,
>(
    ...args: Parameters<typeof getSessionBySessionKeySuspenseQueryOptions<TData, TError>>
) => useSuspenseQuery(getSessionBySessionKeySuspenseQueryOptions<TData, TError>(...args))
