// This file is auto-generated by @hey-api/openapi-ts

import type { UseQueryOptions } from "@tanstack/react-query"

import { queryOptions, useQuery } from "@tanstack/react-query"

import type { PostApiSessionsBySessionKeySyncError } from "@shared/api/generated/types.gen.ts"

import { postSessionBySessionKeySync } from "@shared/api/generated/requests/sessions/postSessionBySessionKeySync.gen.ts"

type PostSessionBySessionKeySyncHookData = Awaited<ReturnType<typeof postSessionBySessionKeySync>>

export const postSessionBySessionKeySyncQueryKey = "postSessionBySessionKeySyncQueryKey"

export const postSessionBySessionKeySyncQueryOptions = <
    TData = PostSessionBySessionKeySyncHookData,
    TError = PostApiSessionsBySessionKeySyncError,
>(settings: {
    params?: Omit<UseQueryOptions<PostSessionBySessionKeySyncHookData, TError, TData>, "queryKey">
    request: NonNullable<Parameters<typeof postSessionBySessionKeySync>[0]>
}) =>
    queryOptions({
        queryKey: [
            postSessionBySessionKeySyncQueryKey,
            ...(!!settings.request.path ? [settings.request.path] : []),
            ...(!!settings.request.query ? [settings.request.query] : []),
            ...(!!settings.request.body ? [settings.request.body] : []),
        ],
        queryFn: async () => postSessionBySessionKeySync({ ...settings.request }),
        ...settings.params,
    })

export const usePostSessionBySessionKeySyncQuery = <
    TData = PostSessionBySessionKeySyncHookData,
    TError = PostApiSessionsBySessionKeySyncError,
>(
    ...args: Parameters<typeof postSessionBySessionKeySyncQueryOptions<TData, TError>>
) => useQuery(postSessionBySessionKeySyncQueryOptions<TData, TError>(...args))
