// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query"

import { useMutation } from "@tanstack/react-query"

import type { PostApiSessionsBySessionKeySyncError } from "@shared/api/generated/types.gen.ts"

import { postSessionBySessionKeySync } from "@shared/api/generated/requests/sessions/postSessionBySessionKeySync.gen.ts"

type PostSessionBySessionKeySyncHookData = Awaited<ReturnType<typeof postSessionBySessionKeySync>>

export const postSessionBySessionKeySyncMutationKey = "postSessionBySessionKeySyncMutationKey"

type PostSessionBySessionKeySyncMutationVariables = Parameters<
    typeof postSessionBySessionKeySync
>[0]

export const usePostSessionBySessionKeySyncMutation = <
    TError = PostApiSessionsBySessionKeySyncError,
    TContext = unknown,
>(settings?: {
    params?: UseMutationOptions<
        PostSessionBySessionKeySyncHookData,
        TError,
        PostSessionBySessionKeySyncMutationVariables,
        TContext
    >
    request?: NonNullable<PostSessionBySessionKeySyncMutationVariables>
}) =>
    useMutation({
        mutationKey: [postSessionBySessionKeySyncMutationKey],
        mutationFn: async (params) =>
            postSessionBySessionKeySync({ ...settings?.request, ...params }),
        ...settings?.params,
    })
